### ISSUE TITLE
GitHub Actions permission issue with texuser UID:2000

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/latex-environment#73]
## 問題

texlive-ja-textlint 2025dへの更新後、GitHub ActionsのBuild and Release PDFワークフローで権限エラーが発生しています。

## エラー詳細

```
Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_*'
```

## 原因

- texlive-ja-textlint 2025dでtexuser UID:2000を使用
- GitHub Actionsランナーのファイルシステムアクセス権限とのミスマッチ
- actions/checkout@v4がRunner APIファイルへの書き込みに失敗

## 影響範囲

- ✅ **DevContainer機能**: 正常動作（主要機能）
- ✅ **LaTeX コンパイル**: 正常動作
- ❌ **GitHub Actions PDF build**: 失敗（テスト環境のみ）

### 短期対応
1. **ワークフローでcontainer userを指定**
   ```yaml
   container:
     image: ghcr.io/smkwlab/texlive-ja-textlint:2025d
     options: --user root
   ```

2. **latex-release-actionの更新**
   - UID:2000対応
   - 権限エラーハンドリング改善

### 長期対応
3. **エコシステム全体でのテスト戦略見直し**
   - DevContainer環境との分離
   - CI専用のイメージ・設定検討

## 関連

- PR #72: Update texlive-ja-textlint to 2025d
- texlive-ja-textlint Issue #23 (解決済み)
- エコシステムPhase 2 dependency update

## 優先度

- **Medium**: DevContainer機能は正常なため
- PRマージ後の対応で問題なし
