### ISSUE TITLE
Improve GitHub Actions code quality: actionlint and security enhancements

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/latex-environment#92]
## Overview

Follow-up issue from #62 to address remaining code quality improvements in GitHub Actions workflows after successful yamllint standardization.

#### 1. Variable Quoting Issues
```bash
# Current issues in multiple workflows:
SC2086: Double quote to prevent globbing and word splitting

# Files affected:
- .github/workflows/check-texlive-updates.yml (multiple locations)
- .github/workflows/create-release.yml (multiple locations)
- .github/workflows/branch-cleanup.yml
```

#### 2. Conditional Logic Improvements
```bash
# Replace \! -z with -n for better shellcheck compliance
SC2236: Use -n instead of \! -z

# Files affected:
- .github/workflows/branch-cleanup.yml (lines 27, 22)
```

#### 3. Command Optimization
```bash
# Improve grep usage
SC2126: Consider using 'grep -c' instead of 'grep|wc -l'

# Improve find syntax
SC2146: This action ignores everything before the -o. Use \( \) to group
```

#### Untrusted Input Handling
```yaml
# Current security warning in pr-auto-cleanup.yml:
# "github.event.pull_request.head.ref" is potentially untrusted

# Solution: Use environment variables
env:
  HEAD_REF: ${{ github.event.pull_request.head.ref }}
run: |
  echo "Processing branch: $HEAD_REF"
```

### 📋 Implementation Tasks

- [ ] Fix variable quoting in check-texlive-updates.yml
- [ ] Fix variable quoting in create-release.yml  
- [ ] Replace \! -z with -n conditions
- [ ] Optimize grep and find commands
- [ ] Secure untrusted input handling in pr-auto-cleanup.yml
- [ ] Add unused variable handling in branch-cleanup.yml
- [ ] Test all changes with actionlint validation

### 🎯 Success Criteria

- [ ] `actionlint .github/workflows/*.yml` produces no warnings
- [ ] All workflows maintain current functionality
- [ ] Security best practices implemented
- [ ] shellcheck compliance achieved

### 🔗 Related

- Continuation of #62 (YAML validation and yamllint configuration)
- Part of ecosystem-wide code quality initiative

### Priority

**Medium** - Improves code quality and security, but workflows are currently functional.
